### ISSUE TITLE
Installing Issue with Processwire 3.0.14

### ISSUE THREAD

**Issue by philschenker** [horst-n/ImageSizerEngineIMagickCLI#1]
Great Module Horst, I like to try it out!

Unfortunately the following Error pops up when I'm trying to install it:

Error: Class 'ProcessWire\ImageSizerEngine' not found (line 11 of D:\xampp\htdocs\pwire3\site\modules\ImageSizerEngineIMagickCLI\ImageSizerEngineIMagickCLI.module) 

I tried to install with the "Module Class Name" that downloads directly from modules.processwire.com and also placed your module in the folder module.

I'm a bit rusty with processwire at the moment. Hope this will change soon.

Thanks for your help

**Comment by horst-n** [comment]
Thanks for pointing that out. But I believe this has to do directly with PW and not with my module. I will try to find out what's wrong here.

**Comment by horst-n** [comment]
@philschenker: do you really used a PW 3.0.14 version? Maybe you can join here in the [PW forum](https://processwire.com/talk/topic/13171-issue-with-installing-third-party-module-through-processwire-3014-classname-download-function/)?

**Comment by philschenker** [comment]
Was on branch master instead of devns. Sorry horst! :-)
